kind: pipeline
name: default

steps:
  - name: test
    image: golang
    environment:
      - GOPROXY=https://goproxy.io,https://goproxy.cn,direct
    commands:
      - go test -v -benchmem -test.bench=".*" -coverprofile=coverage.txt -covermode=atomic  ./...